<?php

/**
 * @file
 * Contains hero_banner.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hero_banner_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hero_banner module.
    case 'help.page.hero_banner':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hero banner with parallax effect') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hero_banner_theme() {
  return [
    'hero_banner' => [
      'variables' => [
        'intro' => NULL,
        'titulo' => NULL,
        'texto' => NULL,
        'texto_link' => NULL,
        'link' => NULL,
        'imagen' => NULL,
      ],
    ],
    'split_banner' => [
      'variables' => [
        'titulo' => NULL,
        'texto' => NULL,
        'texto_link' => NULL,
        'link' => NULL,
        'layout' => NULL,
        'intro' => NULL,
        'imagen' => NULL,
      ],
    ],
    'video_banner' => [
      'variables' => [
        'titulo' => NULL,
        'texto' => NULL,
        'texto_link' => NULL,
        'link' => NULL,
        'imagen' => NULL,
        'mp4_video' => NULL,
        'ogg_video' => NULL,
        'webm_video' => NULL,
      ],
    ],
  ];
}
